title: QuirkyIT
description: "Unique, bespoke IT & cybersecurity services for Australian businesses."
url: "https://quirkyit.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minimal Mistakes config
profile:
  name: QuirkyIT
  email: dean@quirkyit.com.au
  image: /img/Logo.png
navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Services
    url: /services.html
  - title: Contact
    url: /contact.html
