title: QuirkyIT
description: "Unique, bespoke IT & cybersecurity services for Australian businesses."
url: "https://quirkyit.github.io"
baseurl: "https://quirkyit.com.au"
theme: minimal-mistakes-jekyll

# Minimal Mistakes config
profile:
  name: QuirkyIT
  email: dean@quirkyit.com.au
  image: /img/Logo.png
navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Services
    url: /services.html
  - title: Contact
    url: /contact.html
